create database VIAJES;
USE VIAJES;

CREATE TABLE CLIENTES(
	COD INT PRIMARY KEY auto_increment,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(100),
    FNACI DATE,
    EMAIL VARCHAR(200),
    COLORF VARCHAR(20),
    FALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM CLIENTES; 